openapi: 3.1.0
info:
  title: Beckn Core API
  description: Beckn Core API specification
  version: 1.0.0-mop-draft
security:
  - SubscriberAuth: []
  - GatewaySubscriberAuth: []
  - GatewaySubscriberAuthNew: []
paths:
  /search:
    post:
      tags:
        - Beckn Provider Platform (BPP)
        - Beckn Gateway (BG)
      description: This endpoint allows users to search for talents based on various criteria such as skills, karma, and oroganizations.
      requestBody:
        description: BAP searches for services
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: "#/components/schemas/Context"
                message:
                  type: object
                  properties:
                    intent:
                      $ref: "#/components/schemas/Intent"
              required:
                - context
                - message
      responses:
        "200":
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: "#/components/schemas/Ack"
                    required:
                      - ack
                  error:
                    $ref: "#/components/schemas/Error"
                required:
                  - message
